import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { Role } from '@prisma/client';

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return NextResponse.json({ error: 'Neautorizat.' }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const seasonId = searchParams.get('seasonId');
  const search = searchParams.get('search');

  try {
    const where: any = {};
    if (seasonId) where.seasonId = seasonId;
    if (search) {
      where.name = { contains: search, mode: 'insensitive' };
    }

    const events = await prisma.event.findMany({
      where,
      orderBy: { startDate: 'desc' },
      include: {
        season: { select: { id: true, name: true } },
        _count: { select: { days: true } },
      },
    });

    return NextResponse.json(events);
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session || !session.user) {
    return NextResponse.json({ error: 'Neautorizat.' }, { status: 401 });
  }

  const role = (session.user as any).role as Role;
  if (role !== Role.ADMIN && role !== Role.EDITOR) {
    return NextResponse.json({ error: 'Fără drepturi de creare eveniment.' }, { status: 403 });
  }

  try {
    const body = await req.json();
    const { seasonId, name, location, startDate, endDate, autoGenerateDays } = body;

    if (!seasonId || !name || !location || !startDate || !endDate) {
      return NextResponse.json({ error: 'Toate câmpurile sunt obligatorii.' }, { status: 400 });
    }

    const event = await prisma.event.create({
      data: {
        seasonId,
        name,
        location,
        startDate: new Date(startDate),
        endDate: new Date(endDate),
      },
    });

    // Option: Auto-generate days for the event date range
    if (autoGenerateDays) {
      const start = new Date(startDate);
      const end = new Date(endDate);
      const daysToCreate = [];

      let current = new Date(start);
      let dayIndex = 1;

      while (current <= end) {
        daysToCreate.push({
          eventId: event.id,
          date: new Date(current),
          label: `Ziua ${dayIndex}`,
        });
        current.setDate(current.getDate() + 1);
        dayIndex++;
      }

      if (daysToCreate.length > 0) {
        await prisma.day.createMany({
          data: daysToCreate,
        });
      }
    }

    return NextResponse.json(event, { status: 201 });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
