'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { MoveTargetModal } from '@/components/MoveTargetModal';
import { CardActionMenu, CardActionItem } from '@/components/CardActionMenu';
import { Calendar, MapPin, Plus, ChevronRight, Download, Loader2, Sparkles, FolderKanban, Trash2, Pencil, ExternalLink } from 'lucide-react';
import { useSession } from 'next-auth/react';
import { useParams, useRouter } from 'next/navigation';
import { formatDate, toInputDateFormat } from '@/lib/utils';

interface EventItem {
  id: string;
  name: string;
  location: string;
  startDate: string;
  endDate: string;
  _count?: { days: number };
}

interface SeasonDetail {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
}

export default function SeasonEventsPage() {
  const { seasonId } = useParams() as { seasonId: string };
  const { data: session } = useSession();
  const router = useRouter();

  const [season, setSeason] = useState<SeasonDetail | null>(null);
  const [events, setEvents] = useState<EventItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreateModal, setShowCreateModal] = useState(false);

  // Move Event State
  const [eventToMove, setEventToMove] = useState<EventItem | null>(null);

  // Edit Season State (ADMIN only)
  const [showEditSeasonModal, setShowEditSeasonModal] = useState(false);
  const [editSeasonName, setEditSeasonName] = useState('');
  const [editSeasonStartDate, setEditSeasonStartDate] = useState('');
  const [editSeasonEndDate, setEditSeasonEndDate] = useState('');
  const [updatingSeason, setUpdatingSeason] = useState(false);

  // Edit Event State (ADMIN / EDITOR)
  const [eventToEdit, setEventToEdit] = useState<EventItem | null>(null);
  const [editEventName, setEditEventName] = useState('');
  const [editEventLocation, setEditEventLocation] = useState('');
  const [editEventStartDate, setEditEventStartDate] = useState('');
  const [editEventEndDate, setEditEventEndDate] = useState('');
  const [updatingEvent, setUpdatingEvent] = useState(false);

  // Delete states
  const [eventToDelete, setEventToDelete] = useState<EventItem | null>(null);
  const [deletingEvent, setDeletingEvent] = useState(false);
  const [showDeleteSeasonModal, setShowDeleteSeasonModal] = useState(false);
  const [deletingSeason, setDeletingSeason] = useState(false);

  // Create Form state
  const [name, setName] = useState('');
  const [location, setLocation] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [autoGenerateDays, setAutoGenerateDays] = useState(true);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    fetchData();
  }, [seasonId]);

  const fetchData = async () => {
    try {
      const sRes = await fetch('/api/seasons');
      if (sRes.ok) {
        const seasons = await sRes.json();
        const found = seasons.find((s: SeasonDetail) => s.id === seasonId);
        if (found) setSeason(found);
      }

      const eRes = await fetch(`/api/events?seasonId=${seasonId}`);
      if (eRes.ok) {
        const eData = await eRes.json();
        setEvents(eData);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateEvent = async (e: React.FormEvent) => {
    e.preventDefault();
    setCreating(true);

    try {
      const res = await fetch('/api/events', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          seasonId,
          name,
          location,
          startDate,
          endDate,
          autoGenerateDays,
        }),
      });

      if (res.ok) {
        setName('');
        setLocation('');
        setStartDate('');
        setEndDate('');
        setShowCreateModal(false);
        fetchData();
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la crearea evenimentului.');
      }
    } catch (err) {
      console.error(err);
    } finally {
      setCreating(false);
    }
  };

  const handleMoveEventConfirm = async (target: { seasonId?: string }) => {
    if (!eventToMove || !target.seasonId) return;

    try {
      const res = await fetch(`/api/events/${eventToMove.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          targetSeasonId: target.seasonId,
        }),
      });

      if (res.ok) {
        setEventToMove(null);
        fetchData();
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la mutarea evenimentului.');
      }
    } catch (err) {
      console.error(err);
    }
  };

  const openEditSeasonModal = () => {
    if (!season) return;
    setEditSeasonName(season.name);
    setEditSeasonStartDate(toInputDateFormat(season.startDate));
    setEditSeasonEndDate(toInputDateFormat(season.endDate));
    setShowEditSeasonModal(true);
  };

  const handleEditSeason = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!season) return;
    setUpdatingSeason(true);

    try {
      const res = await fetch(`/api/seasons/${season.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: editSeasonName,
          startDate: editSeasonStartDate,
          endDate: editSeasonEndDate,
        }),
      });

      if (res.ok) {
        setShowEditSeasonModal(false);
        fetchData();
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la salvarea modificărilor.');
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUpdatingSeason(false);
    }
  };

  const openEditEventModal = (evt: EventItem) => {
    setEventToEdit(evt);
    setEditEventName(evt.name);
    setEditEventLocation(evt.location);
    setEditEventStartDate(toInputDateFormat(evt.startDate));
    setEditEventEndDate(toInputDateFormat(evt.endDate));
  };

  const handleEditEvent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!eventToEdit) return;
    setUpdatingEvent(true);

    try {
      const res = await fetch(`/api/events/${eventToEdit.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: editEventName,
          location: editEventLocation,
          startDate: editEventStartDate,
          endDate: editEventEndDate,
        }),
      });

      if (res.ok) {
        setEventToEdit(null);
        fetchData();
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la salvarea modificărilor.');
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUpdatingEvent(false);
    }
  };

  const handleDeleteEvent = async () => {
    if (!eventToDelete) return;
    setDeletingEvent(true);

    try {
      const res = await fetch(`/api/events/${eventToDelete.id}`, {
        method: 'DELETE',
      });

      if (res.ok) {
        setEventToDelete(null);
        fetchData();
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la ștergerea evenimentului.');
      }
    } catch (err) {
      console.error(err);
    } finally {
      setDeletingEvent(false);
    }
  };

  const handleDeleteSeason = async () => {
    setDeletingSeason(true);

    try {
      const res = await fetch(`/api/seasons/${seasonId}`, {
        method: 'DELETE',
      });

      if (res.ok) {
        setShowDeleteSeasonModal(false);
        router.push('/');
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la ștergerea sezonului.');
      }
    } catch (err) {
      console.error(err);
    } finally {
      setDeletingSeason(false);
    }
  };

  const role = (session?.user as any)?.role;
  const isAdmin = role === 'ADMIN';
  const canManage = role === 'ADMIN' || role === 'EDITOR';

  if (loading) {
    return (
      <div className="flex items-center justify-center py-24 text-platform-textSecondary space-x-2">
        <Loader2 className="w-6 h-6 animate-spin text-platform-green" />
        <span className="font-mono text-sm">Se încarcă evenimentele...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      
      {/* Breadcrumbs */}
      <Breadcrumbs items={[{ label: season?.name || 'Sezon' }]} />

      {/* Season Header Banner */}
      <div className="platform-card p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-platform-tertiary border border-platform-border">
              <FolderKanban className="w-6 h-6 text-platform-green" />
            </div>
            <h1 className="text-xl sm:text-2xl font-bold font-display text-white">{season?.name}</h1>
          </div>
          {season && (
            <p className="text-xs sm:text-sm text-platform-textSecondary mt-2 flex items-center space-x-2 font-mono">
              <Calendar className="w-3.5 h-3.5 text-platform-green" />
              <span>
                {formatDate(season.startDate)} - {formatDate(season.endDate)}
              </span>
            </p>
          )}
        </div>

        <div className="flex items-center space-x-3">
          {isAdmin && (
            <>
              <button
                onClick={openEditSeasonModal}
                className="p-2.5 rounded-xl bg-platform-tertiary hover:bg-platform-border text-slate-300 hover:text-platform-green border border-platform-border text-xs font-semibold shadow transition flex items-center space-x-1.5 shrink-0 font-mono"
                title="Editează Sezonul"
              >
                <Pencil className="w-4 h-4" />
                <span className="hidden sm:inline">Editează Sezon</span>
              </button>
              <button
                onClick={() => setShowDeleteSeasonModal(true)}
                className="p-2.5 rounded-xl bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 text-xs font-semibold shadow transition flex items-center space-x-1.5 shrink-0 font-mono"
                title="Șterge Sezonul Curent"
              >
                <Trash2 className="w-4 h-4" />
                <span className="hidden sm:inline">Șterge Sezon</span>
              </button>
            </>
          )}

          {canManage && (
            <button
              onClick={() => setShowCreateModal(true)}
              className="btn-platform-primary px-4 py-2.5 text-xs flex items-center space-x-2 shrink-0 shadow"
            >
              <Plus className="w-4 h-4" />
              <span>Adaugă Eveniment Nou</span>
            </button>
          )}
        </div>
      </div>

      {/* Events Grid */}
      {events.length === 0 ? (
        <div className="platform-card text-center py-16">
          <FolderKanban className="w-12 h-12 text-platform-textMuted mx-auto mb-3" />
          <h3 className="text-slate-200 font-semibold text-sm">Nu există evenimente în acest sezon</h3>
          <p className="text-xs text-platform-textSecondary mt-1">Poți adăuga primul eveniment (ex. Regional, Național).</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {events.map((evt) => (
            <div
              key={evt.id}
              className="platform-card p-6 flex flex-col justify-between group hover:border-platform-green/60 transition-all duration-300 shadow-md"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="px-3 py-1 rounded-full bg-platform-green/10 border border-platform-green/20 text-platform-green text-xs font-mono font-semibold">
                    {evt._count?.days || 0} Zile
                  </span>
                  
                  <div className="flex items-center space-x-1.5">
                    <CardActionMenu
                      actions={[
                        ...(canManage ? [
                          {
                            label: 'Mută în alt Sezon',
                            icon: <ExternalLink className="w-4 h-4 text-platform-green" />,
                            onClick: () => setEventToMove(evt),
                            variant: 'primary' as const,
                          },
                          {
                            label: 'Editează Eveniment',
                            icon: <Pencil className="w-4 h-4" />,
                            onClick: () => openEditEventModal(evt),
                          },
                        ] : []),
                        {
                          label: 'Descarcă ZIP',
                          icon: <Download className="w-4 h-4" />,
                          onClick: () => {},
                          href: `/api/download/event/${evt.id}`,
                          download: true,
                        },
                        ...(canManage ? [
                          {
                            label: 'Șterge Eveniment',
                            icon: <Trash2 className="w-4 h-4" />,
                            onClick: () => setEventToDelete(evt),
                            variant: 'danger' as const,
                          },
                        ] : []),
                      ]}
                    />
                  </div>
                </div>

                <Link href={`/events/${evt.id}`} className="block group-hover:text-platform-green transition-colors">
                  <h2 className="text-lg font-bold font-display text-white line-clamp-2">{evt.name}</h2>
                </Link>

                <div className="flex items-center space-x-2 text-xs text-platform-textSecondary">
                  <MapPin className="w-3.5 h-3.5 text-platform-blue shrink-0" />
                  <span className="truncate">{evt.location}</span>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-platform-border/80 flex items-center justify-between text-xs text-platform-textSecondary font-mono">
                <span className="flex items-center space-x-1.5">
                  <Calendar className="w-3.5 h-3.5 text-platform-green" />
                  <span>
                    {formatDate(evt.startDate)} - {formatDate(evt.endDate)}
                  </span>
                </span>
                
                <Link
                  href={`/events/${evt.id}`}
                  className="flex items-center space-x-1 text-xs font-semibold text-platform-green hover:underline"
                >
                  <span>Vezi Galerie / Zile</span>
                  <ChevronRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Move Event Modal */}
      {eventToMove && (
        <MoveTargetModal
          isOpen={Boolean(eventToMove)}
          mode="event"
          itemTitle={eventToMove.name}
          currentSeasonId={seasonId}
          onClose={() => setEventToMove(null)}
          onConfirm={handleMoveEventConfirm}
        />
      )}

      {/* Create Event Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-platform-card border border-platform-border rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <h3 className="font-bold text-lg font-display text-white flex items-center space-x-2">
              <Plus className="w-5 h-5 text-platform-green" />
              <span>Adaugă Eveniment Nou</span>
            </h3>

            <form onSubmit={handleCreateEvent} className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Nume Eveniment</label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Regional Cluj-Napoca 2026"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Locație</label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Sala Polivalentă Cluj"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Început</label>
                  <input
                    type="date"
                    required
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Sfârșit</label>
                  <input
                    type="date"
                    required
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
              </div>

              <label className="flex items-center space-x-2 text-xs text-slate-300 pt-1 cursor-pointer">
                <input
                  type="checkbox"
                  checked={autoGenerateDays}
                  onChange={(e) => setAutoGenerateDays(e.target.checked)}
                  className="rounded border-platform-border bg-platform-bg text-platform-green focus:ring-0"
                />
                <span className="flex items-center space-x-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-platform-green" />
                  <span>Generează automat zilele din intervalul calendaristic</span>
                </span>
              </label>

              <div className="pt-2 flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-xl text-xs font-semibold text-platform-textSecondary hover:bg-platform-tertiary transition"
                >
                  Anulează
                </button>
                <button
                  type="submit"
                  disabled={creating}
                  className="btn-platform-primary px-4 py-2 text-xs flex items-center space-x-1"
                >
                  {creating ? <Loader2 className="w-4 h-4 animate-spin" /> : <span>Salvează</span>}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Season Modal (Admin Only) */}
      {showEditSeasonModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-platform-card border border-platform-border rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <h3 className="font-bold text-lg font-display text-white flex items-center space-x-2">
              <Pencil className="w-5 h-5 text-platform-green" />
              <span>Editează Sezon</span>
            </h3>

            <form onSubmit={handleEditSeason} className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Nume Sezon</label>
                <input
                  type="text"
                  required
                  value={editSeasonName}
                  onChange={(e) => setEditSeasonName(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Început</label>
                  <input
                    type="date"
                    required
                    value={editSeasonStartDate}
                    onChange={(e) => setEditSeasonStartDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Sfârșit</label>
                  <input
                    type="date"
                    required
                    value={editSeasonEndDate}
                    onChange={(e) => setEditSeasonEndDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
              </div>

              <div className="pt-2 flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setShowEditSeasonModal(false)}
                  className="px-4 py-2 rounded-xl text-xs font-semibold text-platform-textSecondary hover:bg-platform-tertiary transition"
                >
                  Anulează
                </button>
                <button
                  type="submit"
                  disabled={updatingSeason}
                  className="btn-platform-primary px-4 py-2 text-xs flex items-center space-x-1"
                >
                  {updatingSeason ? <Loader2 className="w-4 h-4 animate-spin" /> : <span>Salvează Modificările</span>}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Edit Event Modal (Admin / Editor) */}
      {eventToEdit && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-platform-card border border-platform-border rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <h3 className="font-bold text-lg font-display text-white flex items-center space-x-2">
              <Pencil className="w-5 h-5 text-platform-green" />
              <span>Editează Eveniment</span>
            </h3>

            <form onSubmit={handleEditEvent} className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Nume Eveniment</label>
                <input
                  type="text"
                  required
                  value={editEventName}
                  onChange={(e) => setEditEventName(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Locație</label>
                <input
                  type="text"
                  required
                  value={editEventLocation}
                  onChange={(e) => setEditEventLocation(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Început</label>
                  <input
                    type="date"
                    required
                    value={editEventStartDate}
                    onChange={(e) => setEditEventStartDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Sfârșit</label>
                  <input
                    type="date"
                    required
                    value={editEventEndDate}
                    onChange={(e) => setEditEventEndDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
              </div>

              <div className="pt-2 flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setEventToEdit(null)}
                  className="px-4 py-2 rounded-xl text-xs font-semibold text-platform-textSecondary hover:bg-platform-tertiary transition"
                >
                  Anulează
                </button>
                <button
                  type="submit"
                  disabled={updatingEvent}
                  className="btn-platform-primary px-4 py-2 text-xs flex items-center space-x-1"
                >
                  {updatingEvent ? <Loader2 className="w-4 h-4 animate-spin" /> : <span>Salvează Modificările</span>}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Event Confirmation Modal */}
      {eventToDelete && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-platform-card border border-red-500/30 rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <div className="flex items-center space-x-3 text-red-400">
              <div className="p-2.5 rounded-xl bg-red-500/10 border border-red-500/20">
                <Trash2 className="w-6 h-6" />
              </div>
              <h3 className="font-bold text-lg font-display text-white">Ștergere Eveniment</h3>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed">
              Ești sigur că vrei să ștergi evenimentul <strong className="text-white font-semibold">"{eventToDelete.name}"</strong>?
              <br />
              <span className="text-red-400 font-mono text-[11px] block mt-2">
                ⚠️ Toate zilele și fișierele media aferente acestui eveniment vor fi șterse definitiv din baza de date și de pe disc.
              </span>
            </p>

            <div className="pt-2 flex items-center justify-end space-x-3">
              <button
                type="button"
                onClick={() => setEventToDelete(null)}
                disabled={deletingEvent}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-platform-textSecondary hover:bg-platform-tertiary transition"
              >
                Anulează
              </button>
              <button
                type="button"
                onClick={handleDeleteEvent}
                disabled={deletingEvent}
                className="px-4 py-2 rounded-xl text-xs font-semibold bg-red-600 hover:bg-red-500 text-white flex items-center space-x-1.5 transition shadow"
              >
                {deletingEvent ? <Loader2 className="w-4 h-4 animate-spin" /> : <span>Șterge Definitiv</span>}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Season Confirmation Modal */}
      {showDeleteSeasonModal && season && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-platform-card border border-red-500/30 rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <div className="flex items-center space-x-3 text-red-400">
              <div className="p-2.5 rounded-xl bg-red-500/10 border border-red-500/20">
                <Trash2 className="w-6 h-6" />
              </div>
              <h3 className="font-bold text-lg font-display text-white">Ștergere Sezon Curent</h3>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed">
              Ești sigur că vrei să ștergi sezonul <strong className="text-white font-semibold">"{season.name}"</strong>?
              <br />
              <span className="text-red-400 font-mono text-[11px] block mt-2">
                ⚠️ Toate evenimentele, zilele și fișierele media aferente vor fi șterse definitiv.
              </span>
            </p>

            <div className="pt-2 flex items-center justify-end space-x-3">
              <button
                type="button"
                onClick={() => setShowDeleteSeasonModal(false)}
                disabled={deletingSeason}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-platform-textSecondary hover:bg-platform-tertiary transition"
              >
                Anulează
              </button>
              <button
                type="button"
                onClick={handleDeleteSeason}
                disabled={deletingSeason}
                className="px-4 py-2 rounded-xl text-xs font-semibold bg-red-600 hover:bg-red-500 text-white flex items-center space-x-1.5 transition shadow"
              >
                {deletingSeason ? <Loader2 className="w-4 h-4 animate-spin" /> : <span>Șterge Definitiv</span>}
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
