'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { Calendar, MapPin, Plus, ChevronRight, Download, Loader2, Sparkles, FolderKanban } from 'lucide-react';
import { useSession } from 'next-auth/react';
import { useParams } from 'next/navigation';

interface EventItem {
  id: string;
  name: string;
  location: string;
  startDate: string;
  endDate: string;
  _count?: { days: number };
}

interface SeasonDetail {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
}

export default function SeasonEventsPage() {
  const { seasonId } = useParams() as { seasonId: string };
  const { data: session } = useSession();

  const [season, setSeason] = useState<SeasonDetail | null>(null);
  const [events, setEvents] = useState<EventItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [showCreateModal, setShowCreateModal] = useState(false);

  // Form state
  const [name, setName] = useState('');
  const [location, setLocation] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [autoGenerateDays, setAutoGenerateDays] = useState(true);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    fetchData();
  }, [seasonId]);

  const fetchData = async () => {
    try {
      const sRes = await fetch('/api/seasons');
      if (sRes.ok) {
        const seasons = await sRes.json();
        const found = seasons.find((s: SeasonDetail) => s.id === seasonId);
        if (found) setSeason(found);
      }

      const eRes = await fetch(`/api/events?seasonId=${seasonId}`);
      if (eRes.ok) {
        const eData = await eRes.json();
        setEvents(eData);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateEvent = async (e: React.FormEvent) => {
    e.preventDefault();
    setCreating(true);

    try {
      const res = await fetch('/api/events', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          seasonId,
          name,
          location,
          startDate,
          endDate,
          autoGenerateDays,
        }),
      });

      if (res.ok) {
        setName('');
        setLocation('');
        setStartDate('');
        setEndDate('');
        setShowCreateModal(false);
        fetchData();
      } else {
        const err = await res.json();
        alert(err.error || 'A apărut o eroare la crearea evenimentului.');
      }
    } catch (err) {
      console.error(err);
    } finally {
      setCreating(false);
    }
  };

  const role = (session?.user as any)?.role;

  if (loading) {
    return (
      <div className="flex items-center justify-center py-24 text-platform-textSecondary space-x-2">
        <Loader2 className="w-6 h-6 animate-spin text-platform-green" />
        <span className="font-mono text-sm">Se încarcă evenimentele...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      
      {/* Breadcrumbs */}
      <Breadcrumbs items={[{ label: season?.name || 'Sezon' }]} />

      {/* Season Header Banner */}
      <div className="platform-card p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-platform-tertiary border border-platform-border">
              <FolderKanban className="w-6 h-6 text-platform-green" />
            </div>
            <h1 className="text-xl sm:text-2xl font-bold font-display text-white">{season?.name}</h1>
          </div>
          {season && (
            <p className="text-xs sm:text-sm text-platform-textSecondary mt-2 flex items-center space-x-2 font-mono">
              <Calendar className="w-3.5 h-3.5 text-platform-copper" />
              <span>
                {new Date(season.startDate).toLocaleDateString('ro-RO')} - {new Date(season.endDate).toLocaleDateString('ro-RO')}
              </span>
            </p>
          )}
        </div>

        {(role === 'ADMIN' || role === 'EDITOR') && (
          <button
            onClick={() => setShowCreateModal(true)}
            className="btn-platform-primary px-4 py-2.5 text-xs flex items-center space-x-2 shrink-0 shadow"
          >
            <Plus className="w-4 h-4" />
            <span>Adaugă Eveniment Nou</span>
          </button>
        )}
      </div>

      {/* Events Grid */}
      {events.length === 0 ? (
        <div className="platform-card text-center py-16">
          <FolderKanban className="w-12 h-12 text-platform-textMuted mx-auto mb-3" />
          <h3 className="text-slate-200 font-semibold text-sm">Nu există evenimente în acest sezon</h3>
          <p className="text-xs text-platform-textSecondary mt-1">Poți adăuga primul eveniment (ex. Regional, Național).</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {events.map((evt) => (
            <div
              key={evt.id}
              className="platform-card p-6 flex flex-col justify-between group hover:border-platform-copper/60 transition-all duration-300 shadow-md"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="px-3 py-1 rounded-full bg-platform-copper/10 border border-platform-copper/20 text-platform-copper text-xs font-mono font-semibold">
                    {evt._count?.days || 0} Zile
                  </span>
                  
                  {/* Download Event ZIP Button */}
                  <a
                    href={`/api/download/event/${evt.id}`}
                    download
                    className="p-2 rounded-xl bg-platform-tertiary hover:bg-platform-copper/20 text-slate-300 hover:text-platform-copper transition border border-platform-border"
                    title="Descarcă toate fișierele evenimentului ca ZIP"
                  >
                    <Download className="w-4 h-4" />
                  </a>
                </div>

                <Link href={`/events/${evt.id}`} className="block group-hover:text-platform-green transition-colors">
                  <h2 className="text-lg font-bold font-display text-white line-clamp-2">{evt.name}</h2>
                </Link>

                <div className="flex items-center space-x-2 text-xs text-platform-textSecondary">
                  <MapPin className="w-3.5 h-3.5 text-platform-blue shrink-0" />
                  <span className="truncate">{evt.location}</span>
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-platform-border/80 flex items-center justify-between text-xs text-platform-textSecondary font-mono">
                <span className="flex items-center space-x-1.5">
                  <Calendar className="w-3.5 h-3.5 text-platform-copper" />
                  <span>
                    {new Date(evt.startDate).toLocaleDateString('ro-RO')} - {new Date(evt.endDate).toLocaleDateString('ro-RO')}
                  </span>
                </span>
                
                <Link
                  href={`/events/${evt.id}`}
                  className="flex items-center space-x-1 text-xs font-semibold text-platform-green hover:underline"
                >
                  <span>Vezi Zilele</span>
                  <ChevronRight className="w-4 h-4" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create Event Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-platform-card border border-platform-border rounded-2xl w-full max-w-md p-6 space-y-4 shadow-2xl">
            <h3 className="font-bold text-lg font-display text-white flex items-center space-x-2">
              <Plus className="w-5 h-5 text-platform-blue" />
              <span>Adaugă Eveniment Nou</span>
            </h3>

            <form onSubmit={handleCreateEvent} className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Nume Eveniment</label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Regional Cluj-Napoca 2026"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="space-y-1">
                <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Locație</label>
                <input
                  type="text"
                  required
                  placeholder="Ex: Sala Polivalentă Cluj"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Început</label>
                  <input
                    type="date"
                    required
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold uppercase text-platform-textSecondary font-mono">Data Sfârșit</label>
                  <input
                    type="date"
                    required
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full px-3 py-2 bg-platform-bg border border-platform-border rounded-xl text-xs text-white focus:outline-none focus:border-platform-green"
                  />
                </div>
              </div>

              <label className="flex items-center space-x-2 text-xs text-slate-300 pt-1 cursor-pointer">
                <input
                  type="checkbox"
                  checked={autoGenerateDays}
                  onChange={(e) => setAutoGenerateDays(e.target.checked)}
                  className="rounded border-platform-border bg-platform-bg text-platform-green focus:ring-0"
                />
                <span className="flex items-center space-x-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-platform-copper" />
                  <span>Generează automat zilele din intervalul calendaristic</span>
                </span>
              </label>

              <div className="pt-2 flex items-center justify-end space-x-3">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-xl text-xs font-semibold text-platform-textSecondary hover:bg-platform-tertiary transition"
                >
                  Anulează
                </button>
                <button
                  type="submit"
                  disabled={creating}
                  className="btn-platform-primary px-4 py-2 text-xs flex items-center space-x-1"
                >
                  {creating ? <Loader2 className="w-4 h-4 animate-spin" /> : <span>Salvează</span>}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
